SELECT a.CUST_NO ,b.SGSH_TX_CODE,a.THIS_VOL_BAL-a.ABNORMAL_FRZN_VOL-a.SELL_FROZEN_VOL-a.ETF_FROZEN_VOL-a.NOT_CIRC_VOL-a.MANUAL_FROZEN_VOL AS VOL_BAL FROM KS.STOCK a
		LEFT JOIN
		KS.ETF_BASE_INFO b
		ON  a.SEC_CODE = b.BS_CODE
		WHERE a.MARKET_CODE = '{}' AND b.BS_CODE IS NOT NULL AND a.CUR_BUY_VOL = '0' AND a.CUR_SELL_VOL = '0' AND a.SEC_CODE = '{}'	  {}{}
		 AND a.CUST_NO IN (
							 SELECT D1.CUST_NO FROM KS.HOLDER_ACC D1 LEFT JOIN KS.CUST_BASE_INFO BB1 ON D1.CUST_NO = BB1.CUST_NO
                    		 WHERE D1.HOLDER_ACC_NO !='' AND BB1.CUST_STATUS = '0' AND D1.STATUS = '0'{}{} AND BB1.ATTRIBUTE = '0' AND BB1.CUST_NO NOT IN {} AND D1.HOLDER_TYPE IN ('00','04')
                    )
		ORDER BY VOL_BAL DESC FETCH FIRST 1 ROWS ONLY WITH UR
