SELECT CUST_NO,SEC_CODE ,a.THIS_VOL_BAL-a.ABNORMAL_FRZN_VOL-a.SELL_FROZEN_VOL-a.ETF_FROZEN_VOL-a.NOT_CIRC_VOL-a.MANUAL_FROZEN_VOL AS VOL_BAL FROM KS.STOCK a
WHERE SEC_CODE  IN (SELECT SEC_CODE FROM KS.B_SEC_CODE
                    WHERE SEC_CODE IN (SELECT COMPANY_CODE FROM KS.VOTE_MEETING_INFO) WITH UR)
AND a.MARKET_CODE = '{}' AND a.CUST_NO IN (
					SELECT D1.CUST_NO FROM KS.HOLDER_ACC D1 LEFT JOIN KS.CUST_BASE_INFO BB1 ON D1.CUST_NO = BB1.CUST_NO
                    WHERE D1.HOLDER_ACC_NO !='' AND BB1.CUST_STATUS = '0'   AND D1.STATUS = '0' {}{} AND BB1.ATTRIBUTE = '0' AND D1.HOLDER_TYPE IN ('00','04'))
AND a.CUST_NO NOT IN {} {}{}

ORDER BY VOL_BAL DESC FETCH FIRST 1 ROWS ONLY WITH UR;