SELECT AA.CUST_NO,BB.SEC_CODE FROM (
SELECT a.CUST_NO,a.SEC_TYPE,b.SEC_CODE,
		a.THIS_VOL_BAL-a.ABNORMAL_FRZN_VOL-a.SELL_FROZEN_VOL-a.ETF_FROZEN_VOL-a.NOT_CIRC_VOL AS VOL_BAL
		FROM KS.STOCK a
		
		LEFT JOIN KS.MORTGAGE B
		ON a.CUST_NO = B.CUST_NO
		WHERE a.SEC_CODE = '888880' AND a.MARKET_CODE = '{}' AND B.CUST_NO IS NOT NULL  AND a.HOLDER_ACC_NO IN (
 					SELECT D1.HOLDER_ACC_NO  FROM KS.HOLDER_ACC D1   WHERE D1.HOLDER_ACC_NO !=''  {}{} AND D1.STATUS = '0' AND D1.HOLDER_TYPE IN ('00','04') )
 					{}{}
		)
		AA
		LEFT JOIN KS.B_SEC_CODE
		BB
		ON AA.SEC_CODE = BB.SEC_CODE
	   WHERE  AA.CUST_NO NOT IN {} AND  BB.SEC_CODE IS NOT NULL  AND AA.SEC_CODE IN (SELECT SEC_CODE FROM KS.BOND_UNTRADE_INFO WHERE BS = '0l' )
	   AND BB.SEC_TYPE = '{}' AND BB.SEC_VARIETY = '{}'
	   ORDER BY AA.VOL_BAL DESC FETCH FIRST 1 ROWS ONLY WITH UR



