SELECT a.sec_code FROM KS.XG_INFORMATION a
LEFT JOIN 
KS.B_SEC_CODE b
ON a.SEC_CODE = b.SEC_CODE 
WHERE a.MARKET_CODE = '{}' AND b.SEC_TYPE = '{}' AND b.SEC_VARIETY = '{}' AND b.SEC_LEVEL = '0' AND b.SEC_SHORT_NAME !='新增证券'  AND b.EXCHANGE_SEC_TYPE = '8'
ORDER BY rand()FETCH FIRST 1 ROWS ONLY WITH UR 