	   SELECT a.CUST_NO,D1.SEC_CODE,
	   a.THIS_VOL_BAL-a.ABNORMAL_FRZN_VOL-a.SELL_FROZEN_VOL-a.ETF_FROZEN_VOL-a.NOT_CIRC_VOL-a.MANUAL_FROZEN_VOL AS VOL_BAL

	   FROM KS.STOCK a

		LEFT JOIN KS.MORTGAGE D1
		ON a.CUST_NO = D1.CUST_NO
		WHERE a.SEC_CODE = '131990' AND a.MARKET_CODE = '{}' AND a.CUST_NO NOT IN {} AND  D1.CUST_NO IS NOT NULL
		{}{}
	     AND (a.THIS_VOL_BAL-a.ABNORMAL_FRZN_VOL-a.SELL_FROZEN_VOL-a.ETF_FROZEN_VOL-a.NOT_CIRC_VOL-a.MANUAL_FROZEN_VOL) >0
	    {}{}
		ORDER BY VOL_BAL DESC FETCH FIRST 1 ROWS ONLY WITH UR


