
SELECT sec_code FROM KS.B_SEC_CODE
WHERE SEC_TYPE = '{}' AND SEC_VARIETY = '{}' AND MARKET_CODE = '{}' and sec_code in (SELECT sec_code FROM KS.TENDERER_INFO)
ORDER BY rand()  FETCH FIRST 1 ROWS ONLY WITH UR


