SELECT a.CUST_NO,a.SEC_CODE FROM
KS.BJ_BOND a
LEFT JOIN KS.BJ_SEC_CODE b
ON a.SEC_CODE = b.SEC_CODE
WHERE a.MARKET_CODE = '{}'  AND a.BACK_DATE > (SELECT replace(CHAR(CURRENT DATE),'-','') FROM SYSIBM.SYSDUMMY1)
AND b.sec_code IS NOT NULL AND a.USER_AUTO_CONTINUE = '1' and HAVE_CONTINUE='0' AND CANCEL_FLAG <> '1'
AND a.CUST_NO IN (SELECT D1.CUST_NO FROM KS.HOLDER_ACC D1 LEFT JOIN KS.CUST_BASE_INFO BB1 ON D1.CUST_NO = BB1.CUST_NO
                    WHERE D1.HOLDER_ACC_NO !='' AND BB1.CUST_STATUS = '0' AND D1.STATUS = '0' {}{} AND BB1.ATTRIBUTE = '0' AND BB1.CUST_NO NOT IN {} AND D1.HOLDER_TYPE IN ('00','04') )
{}{}
FETCH FIRST 1 ROWS ONLY WITH UR ;