   SELECT CUST_NO  FROM KS.CUST_BASE_INFO WHERE CUST_NO IN (
		SELECT AA.CUST_NO FROM (SELECT A.CUST_NO,A.CUST_STATUS FROM KS.CUST_BASE_INFO A
			LEFT JOIN
			(SELECT CUST_NO FROM KS.VIP_CUST_LIST)B
			 ON A.CUST_NO = B.CUST_NO
			 WHERE B.CUST_NO IS NULL AND A.ATTRIBUTE = '0' )AA
			 LEFT JOIN
			 (SELECT D1.CUST_NO,a.THIS_BAL FROM KS.HOLDER_ACC D1 LEFT JOIN KS.FUND a ON D1.CUST_NO = a.CUST_NO WHERE  D1.MARKET_CODE = '{market_code}'
			 AND D1.CUST_NO NOT IN {cust_no_N} AND D1.STATUS = '0' {tmp_seatno_Y}{tmp_seatno_N} AND a.CUST_NO IS NOT NULL  {Y_branch_code}{N_branch_code}
			 )BB
			 ON AA.CUST_NO = BB.CUST_NO
			 WHERE BB.CUST_NO IS NOT NULL AND AA.CUST_STATUS = '0'
			 ORDER BY BB.THIS_BAL DESC FETCH FIRST 20 ROWS ONLY WITH UR) AND CUST_NO NOT IN (SELECT CUST_NO FROM KS.REST_CUST_EXEMPT )
			 ORDER BY rand() FETCH FIRST 1 ROWS ONLY WITH UR
